name: Build German Artical Trainer
on: [push]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y git zip unzip python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev
          pip3 install --user --upgrade Cython==0.29.33 virtualenv buildozer

      - name: Unzip Stage Data
        run: |
          if [ -f "data.zip" ]; then
            unzip data.zip -d .
          fi

      - name: Build with Buildozer
        run: |
          # Use the --accept-sdk-license flag to prevent stopping for prompts
          ~/.local/bin/buildozer -v android debug
        env:
          # This tells the build to automatically accept Android licenses
          APP_ANDROID_ACCEPT_SDK_LICENSE: "True"

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: GermanTrainer-APK
          path: bin/*.apk
